### ISSUE TITLE
복사 허락 및 몇가지 질문입니다.

### ISSUE THREAD

**Issue by ayogom** [inasie/apt-trade-info#1]
안녕하세요
어제 우연찮게 소스를 보다가, 제 깃허브로 포크해버렸는데요
일단 오늘 라이센스 업데이트를 보니, 광고 목적은 사용을 불허 하신다고해서,
소스 코드내에 광고는 삭제 했습니다.

저는 광주지역에 대해서 집중해서... 분석을 하고 싶은데요, 몇가지 소스코드를 좀 사용해도 될까요?
광주 이외의 지역은 inasie 님의 페이지로 연결을 걸었습니다.

그리고, 실거래에서 이해가 안되는게, 공공데이터 포탈에서는 월단위로 신고가 이뤄지는데,
일 단위로 추출 하는 방법이 따로 있을까요? 아니면 월단위에서 차분을 계속 처리하는 방식일까요?

**Comment by inasie** [comment]
1. 광고를 제거하셨다면 코드자체를 분석/사용하시는걸 막지않습니다. 
2. 공공데이터포털자료를 가공(추출)해서 생성한 웹페이지를 github.io를 이용해 배포하는것입니다.
3. 페이지 포멧이 계속 변경중이라 감안하셔야합니다

**Comment by ayogom** [comment]
넵 감사합니다. 아마도 페이지 포멧 쪽은 제가 다시 정렬을 할 것 같습니다.
